package GUI;
import Database.database;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.*;
import Entitas.jadwalmemasak;
import Entitas.pengguna;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Silva_Jen_Retno
 */
public class MenuUtama extends javax.swing.JFrame {

    private database db;
    public int id;
    private pengguna pengguna;
    private DefaultTableCellRenderer cellRenderer;
    
    private String convertColumnName(String selectedColumn) {
        switch (selectedColumn) {
            case "ID":
                return "Id_Jadwal";
            case "Nama":
                return "Nama_Makanan";
            default:
                return ""; // Nilai default jika tidak ada yang cocok
        }
    }

    
    private void populateTable() {
       DefaultTableModel model = new DefaultTableModel() {
           @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
       };
       model.setColumnIdentifiers(new Object[]{"ID", "Name", "Food Category", "Day", "Date", "Budget"});

       try {
            database db = new database();
            db.openConnection();
            db.statement = db.connection.createStatement();
           
            String query = "SELECT * FROM jadwal_memasak";
           try (ResultSet resultSet = db.statement.executeQuery(query)) {
               while (resultSet.next()) {
                   id = resultSet.getInt("Id_Jadwal");
                   String nama = resultSet.getString("Nama_Makanan");
                   String jenis = resultSet.getString("Jenis_Makanan");
                   String hari = resultSet.getString("Hari_Memasak");
                   String tanggal = resultSet.getString("Tanggal");
                   String budget = resultSet.getString("Budget");
                   model.addRow(new Object[]{id, nama, jenis, hari, tanggal, budget});
               }
               
           }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
           if (tabel == null) {
            tabel = new JTable(model);
            tabel.setColumnSelectionAllowed(false); // Tidak memperbolehkan pemilihan kolom
            tabel.setCellSelectionEnabled(true); // Memperbolehkan pemilihan sel
            tabel.setRowSelectionAllowed(true);
            JScrollPane scrollPane = new JScrollPane(tabel);
            add(scrollPane);
        } else {
           tabel.setModel(model);
        }
           DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
           centerRenderer.setHorizontalAlignment( JLabel.CENTER );
           tabel.getColumnModel().getColumn(0).setPreferredWidth(20);
           tabel.getColumnModel().getColumn(1).setPreferredWidth(45);
           tabel.getColumnModel().getColumn(2).setPreferredWidth(60);
           tabel.getColumnModel().getColumn(3).setPreferredWidth(45);
           tabel.getColumnModel().getColumn(4).setPreferredWidth(60);
           tabel.getColumnModel().getColumn(5).setPreferredWidth(30);
           tabel.setModel(model);
      }
    }
    
    public MenuUtama(pengguna pengguna) throws ClassNotFoundException, SQLException {
        initComponents();
        populateTable();
        db = new database();
        this.pengguna = pengguna;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        SearchValue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        NamaKolom = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("KitchenScheduler");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 20, -1, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("______________________");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Note down your cooking schedule here..");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        tabel.setBackground(new java.awt.Color(232, 183, 217));
        tabel.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        tabel.setForeground(new java.awt.Color(0, 0, 0));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis", "Hari", "Tanggal", "Budget"
            }
        ));
        tabel.setGridColor(new java.awt.Color(255, 102, 255));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 400, 190));

        add.setBackground(new java.awt.Color(232, 183, 217));
        add.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setText("ADD");
        add.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 40));

        update.setBackground(new java.awt.Color(232, 183, 217));
        update.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        update.setForeground(new java.awt.Color(0, 0, 0));
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 40));

        delete.setBackground(new java.awt.Color(232, 183, 217));
        delete.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("DELETE");
        delete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 40));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setText("EXIT");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 80, 30));

        SearchValue.setBackground(new java.awt.Color(255, 255, 255));
        SearchValue.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        SearchValue.setForeground(new java.awt.Color(0, 0, 0));
        SearchValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(SearchValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 110, 30));

        jButton1.setBackground(new java.awt.Color(232, 183, 217));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("SEARCH");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 60, 30));

        NamaKolom.setBackground(new java.awt.Color(232, 183, 217));
        NamaKolom.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        NamaKolom.setForeground(new java.awt.Color(0, 0, 0));
        NamaKolom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nama" }));
        getContentPane().add(NamaKolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 70, 30));

        jLabel1.setBackground(new java.awt.Color(232, 183, 217));
        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Menu Utama.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Add tambah = new Add(this.pengguna);
        this.dispose();
        tambah.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Update ubah = new Update(this.pengguna);
        this.dispose();
        ubah.setVisible(true);
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String Id_Jadwal = JOptionPane.showInputDialog("Masukan ID : ", null);

//        // Validasi input, pastikan ID yang akan dihapus tidak kosong
        if (Id_Jadwal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
             jadwalmemasak datajadwal = new jadwalmemasak(id, null, null, null, null, 0, null);
            boolean createSuccess =  datajadwal.delete();
            if (createSuccess) {
                JOptionPane.showMessageDialog(null, "Jadwal berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        try {
            // TODO add your handling code here:
            new Login().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedColumn = NamaKolom.getSelectedItem().toString(); // Mendapatkan nama kolom yang dipilih
        String columnName = convertColumnName(selectedColumn); // Mengkonversi ke nama kolom yang sesuai
        String searchValue = SearchValue.getText(); // Mendapatkan nilai yang ingin dicari

        DefaultTableModel model = new DefaultTableModel() {
           @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
       };
       model.setColumnIdentifiers(new Object[]{"ID", "Name", "Food Category", "Day", "Date", "Budget"});
       
        try {
            database db = new database();
            db.openConnection();
            db.statement = db.connection.createStatement();

            String query = "SELECT * FROM jadwal_memasak";

            // Jika SearchValue tidak kosong, tambahkan kondisi pencarian ke query
            if (!searchValue.isEmpty()) {
                query += " WHERE " + columnName + " = '" + searchValue + "'";

            }


            try (ResultSet resultSet = db.statement.executeQuery(query)) {
               while (resultSet.next()) {
                   id = resultSet.getInt("Id_Jadwal");
                   String nama = resultSet.getString("Nama_Makanan");
                   String jenis = resultSet.getString("Jenis_Makanan");
                   String hari = resultSet.getString("Hari_Memasak");
                   String tanggal = resultSet.getString("Tanggal");
                   String budget = resultSet.getString("Budget");
                   model.addRow(new Object[]{id, nama, jenis, hari, tanggal, budget});
               }
               
           }
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        } finally {
            
            if (searchValue.isEmpty()) {
            populateTable();
            return;
            }
            
           if (tabel == null) {
            tabel = new JTable(model);
            tabel.setColumnSelectionAllowed(false); // Tidak memperbolehkan pemilihan kolom
            tabel.setCellSelectionEnabled(true); // Memperbolehkan pemilihan sel
            tabel.setRowSelectionAllowed(true);
            JScrollPane scrollPane = new JScrollPane(tabel);
            add(scrollPane);
        } else {
           tabel.setModel(model);
        }
           DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
           centerRenderer.setHorizontalAlignment( JLabel.CENTER );
           tabel.getColumnModel().getColumn(0).setPreferredWidth(20);
           tabel.getColumnModel().getColumn(1).setPreferredWidth(45);
           tabel.getColumnModel().getColumn(2).setPreferredWidth(60);
           tabel.getColumnModel().getColumn(3).setPreferredWidth(45);
           tabel.getColumnModel().getColumn(4).setPreferredWidth(60);
           tabel.getColumnModel().getColumn(5).setPreferredWidth(30);
           tabel.setModel(model);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuUtama(null).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> NamaKolom;
    private javax.swing.JTextField SearchValue;
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
