package GUI;

import Database.database;
import Entitas.jadwalmemasak;
import Entitas.pengguna;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Silva_Jen_Retno
 */
public class Update extends javax.swing.JFrame {
    private database db;
    private pengguna pengguna;
    
    /**
     * Creates new form Update
     */
    public Update(pengguna pengguna) {
        initComponents();
        this.pengguna = pengguna;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        jenis = new javax.swing.JComboBox<>();
        hari = new javax.swing.JComboBox<>();
        tanggal = new com.toedter.calendar.JDateChooser();
        budget = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        idjadwal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 220, -1));

        jenis.setBackground(new java.awt.Color(255, 255, 255));
        jenis.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jenis.setForeground(new java.awt.Color(0, 0, 0));
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast", "Lunch", "Dinner" }));
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 220, -1));

        hari.setBackground(new java.awt.Color(255, 255, 255));
        hari.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        hari.setForeground(new java.awt.Color(0, 0, 0));
        hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        getContentPane().add(hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 220, -1));

        tanggal.setBackground(new java.awt.Color(255, 255, 255));
        tanggal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 220, -1));

        budget.setBackground(new java.awt.Color(255, 255, 255));
        budget.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        budget.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(budget, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 220, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("KitchenScheduler");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 24, 120, 20));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Note down your cooking schedule here..");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Food Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 20));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Day");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Budget");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, 40));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 11)); // NOI18N
        update.setForeground(new java.awt.Color(0, 0, 0));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 100, 30));

        idjadwal.setBackground(new java.awt.Color(255, 255, 255));
        idjadwal.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        idjadwal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(idjadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 220, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 100, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CRUD.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            String nm = nama.getText();
            String jn = (String) jenis.getSelectedItem();
            String hr = (String) hari.getSelectedItem();
//            String iu = idu.getText();
            
            java.util.Date utilDate = tanggal.getDate();
            java.sql.Date sqlDate = null;
            if (utilDate != null) {
                sqlDate = new java.sql.Date(utilDate.getTime());
//                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                java.util.Date tg = tanggal.getDate();
            } else {
                JOptionPane.showMessageDialog(null, "Pilih tanggal terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int bg = 0;
            int id = 0;
            
            try {
            bg = Integer.parseInt(budget.getText());
            id = Integer.parseInt(idjadwal.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Isi dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;  // Exit the method if parsing fails.
            }
            
            if (nm.isEmpty() || jn.isEmpty() || hr.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Semua kolom harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
                jadwalmemasak jadwal = new jadwalmemasak(id,nm, jn, hr, sqlDate, bg, this.pengguna.ID_User);
                jadwal.setNama_Makanan(nm);
                jadwal.setJenis_Makanan(jn);
                jadwal.setHari_Memasak(hr);
                jadwal.setTanggal(sqlDate);
                jadwal.setBudget(bg);
                jadwal.setPENGGUNA_ID_User(this.pengguna.ID_User);
                
                boolean createSuccess = jadwal.ubahjadwalmemasak();
                

            if (createSuccess) {
                JOptionPane.showMessageDialog(null, "Jadwal berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui jadwal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            idjadwal.setText("");
            nama.setText("");
            jenis.setSelectedItem(null);
            hari.setSelectedItem(null);
            tanggal.setDate(null);
            budget.setText("");
//            idu.setText(this.pengguna.ID_User);
            }
            
        } catch (Exception e) {
            e.printStackTrace(); // Cetak detail pengecualian untuk membantu identifikasi masalah
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new MenuUtama(this.pengguna).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budget;
    private javax.swing.JComboBox<String> hari;
    private javax.swing.JTextField idjadwal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField nama;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
